### ISSUE TITLE
Frontmatter

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/data-literacies#10]
Hi @dyoong ! 

Few comments on the frontmatter file:

- I fixed some minor typos, punctuation, and links 
- In the opening blurb, I would try and provide at least a provisional answer to the question you pose (What is data?) or maybe you could start with a list of what constitutes data and then ask the question? Just thinking that it might be useful for participants to have a better sense of what they are getting into and why it matters right away. 
- Acknowledgments: This is more of a question for @kallewesterling than a comment per se. Did we settle on a specific format this section? For my own workshop, I ended up copying  what @lmrhody did – here it is, in case you want  to do the same @dyoong 
<img width="252" alt="Screen Shot 2020-07-19 at 2 02 22 PM" src="https://user-images.githubusercontent.com/35434644/87874238-79a94500-c9c8-11ea-839b-4549f435db48.png">

**Comment by kallewesterling** [comment]
As for the acknowledgements I'll just pop in and say that you can format them as you see fit but they should follow the convention:

```md
- Role: <first-name> <last-name>
```

There should only be _one person per each line_. That's all. If you want to go more advanced, you have some options:

---

- If you want to, you can also add a link:

   ```md
   - Role: [<first-name> <last-name>](<website>)
   ```

- You can also leave the role out completely, and either include a link or not:

   ```md
   - <first-name> <last-name>
   ```

   ```md
   - [<first-name> <last-name>](<website>)
   ```
