### ISSUE TITLE
Central markdown files finalized

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/data-literacies#13]
### `lessons.md`

- [x] Accept any [pending pull requests](../pulls)

- [x] Implement all [the edits/requests](https://github.com/DHRI-Curriculum/data-literacies/issues/12) that you have left from your colleagues.

- [x] Add any additional content you think is needed for version 2.0 _and open any other using the [![](https://img.shields.io/github/labels/dhri-curriculum/data-literacies/wishlist)](../labels/wishlist) label in your repo

- [x] Ensure the length of each lesson is not too long
    _each section (beginning with a level 1 heading [#]) should be no more than 3-4 paragraphs_

- [x] Ensure temporal references and references to other workshops are removed (since learners will “attend” these workshops mostly asynchronously)

### `frontmatter.md`

- [x] Finalize and streamline all sections

- [x] Ensure your abstract is no longer than ~100 words
   _If you need/want them to be longer, you can create a new first section in lessons.md and put the longer version of the abstract there._

- [x] Resolve any "TBD" content.

- [x] Make sure collaborator lists are complete with roles and links
   _see [Di’s example](https://github.com/DHRI-Curriculum/data-literacies/blob/v2.0-di-edits/frontmatter.md#acknowledgements) but feel free to add links to people’s websites!_

- [x] Ensure all Projects and Readings have "annotations"
   _annotations = 1-2 sentences answering “Why is it important for our learners to read or expose themselves to these readings/projects”? For examples, see [agenda doc](https://docs.google.com/document/d/18MImAjxv3_cYKuGvnvsLS0L8Dkn8jSluMxOjeWv2G8k/edit#)_

### `theory-to-practice.md`

- [x] Finalize and streamline all sections

- [x] Resolve any "TBD" content.

- [x] Ensure all Projects, Readings, and Tutorials have "annotations"
   _annotations = 1-2 sentences answering “Why is it important for our learners to read or expose themselves to these readings/projects”? For examples, see [agenda doc](https://docs.google.com/document/d/18MImAjxv3_cYKuGvnvsLS0L8Dkn8jSluMxOjeWv2G8k/edit#)_

**Comment by dyoong** [comment]
@kallewesterling I have a question about linking to other repos, I know you mentioned to remove them, but I was wondering if I am trying to link to a concept (e.g. version control in git) should I still remove the link? Thanks.

**Comment by kallewesterling** [comment]
Is that a link to a specific lesson? Or did you mean a glossary term?

**Comment by dyoong** [comment]
I could link it to the glossary term if it is out. Right now it's linked to the specific section in the repo.

**Comment by kallewesterling** [comment]
@dyoong I see that there is one bulletpoint that is not checked above. If you are done with this issue, can you check that and close out the issue since we have moved into the final `sprint 5` now?
