### ISSUE TITLE
Make links absolute

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/data-literacies#7]
For the website script to fully include your linked files, they need to have an absolute URL, so a link to `files/cats.csv` needs to be `https://raw.githubusercontent.com/DHRI-Curriculum/Data-and-Ethics/v2.0-di-edits/files/cats.csv`.

The easiest way to find the link is by navigating to the file in your repo:

![image](https://user-images.githubusercontent.com/7298727/87469434-455d0f80-c5e9-11ea-99fe-6e1432c1dfc2.png)

And then clicking the "Raw" button:

![image](https://user-images.githubusercontent.com/7298727/87469453-4e4de100-c5e9-11ea-9443-f833765327eb.png)

The URL in your window is the one that you want to insert into the markdown link.

**Comment by dyoong** [comment]
I can't get a raw link for the xlsx file. Can it be the "https://github.com/DHRI-Curriculum/Data-and-Ethics/blob/v2.0-di-edits/files/cats.xlsx" link instead?

**Comment by dyoong** [comment]
Oh, and do the images have to be pulled in with the absolute URL too?

**Comment by kallewesterling** [comment]
That link seems to work fine, @dyoong - it's just a matter of relative links not working when we pull the content from here to the local webserver.

Images don't, because I have built a whole system around them to try to parse all of them. It broke today but I'll fix it soon :)

**Comment by kallewesterling** [comment]
Looks good to me @dyoong  so I will go ahead and close this issue. Feel free to reopen if you think we should review more.
